'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class accesorio
    Public Property id As Integer
    Public Property nombre As String
    Public Property tipo_accesorio As Integer
    Public Property detalles As String

    Public Overridable Property tipo_accesorio1 As tipo_accesorio
    Public Overridable Property chequeo_accesorio As ICollection(Of chequeo_accesorio) = New HashSet(Of chequeo_accesorio)

End Class
