'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class chequeo_accesorio
    Public Property chequeo_id As Integer
    Public Property accesorio_id As Integer
    Public Property valor As Boolean

    Public Overridable Property accesorio As accesorio
    Public Overridable Property chequeo As chequeo

End Class
