'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class chequeo
    Public Property id As Integer
    Public Property id_usuario As Integer
    Public Property id_vehiculo As Integer
    Public Property fecha As Date
    Public Property tipo As String
    Public Property kilometraje As Integer
    Public Property combustible As Integer
    Public Property detalles As String
    Public Property activo As Boolean

    Public Overridable Property chequeo_accesorio As ICollection(Of chequeo_accesorio) = New HashSet(Of chequeo_accesorio)
    Public Overridable Property usuario As usuario
    Public Overridable Property vehiculo As vehiculo

End Class
