'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class Chequeo_de_VehiculosEntities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Chequeo_de_VehiculosEntities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagram)
    Public Overridable Property accesorios() As DbSet(Of accesorio)
    Public Overridable Property chequeos() As DbSet(Of chequeo)
    Public Overridable Property chequeo_accesorio() As DbSet(Of chequeo_accesorio)
    Public Overridable Property nivels() As DbSet(Of nivel)
    Public Overridable Property permisoes() As DbSet(Of permiso)
    Public Overridable Property tipo_accesorio() As DbSet(Of tipo_accesorio)
    Public Overridable Property usuarios() As DbSet(Of usuario)
    Public Overridable Property vehiculoes() As DbSet(Of vehiculo)
    Public Overridable Property vehiculo_estado() As DbSet(Of vehiculo_estado)

End Class
