'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class permiso
    Public Property id As Integer
    Public Property nombre As String
    Public Property detalles As String
    Public Property periodos_renovacion As Integer
    Public Property activo As Boolean

    Public Overridable Property vehiculoes As ICollection(Of vehiculo) = New HashSet(Of vehiculo)

End Class
