'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tipo_accesorio
    Public Property id As Integer
    Public Property nombre As String
    Public Property detalles As String

    Public Overridable Property accesorios As ICollection(Of accesorio) = New HashSet(Of accesorio)

End Class
