'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class usuario
    Public Property id As Integer
    Public Property usuario1 As String
    Public Property clave As String
    Public Property nivel As Integer
    Public Property activo As Boolean

    Public Overridable Property chequeos As ICollection(Of chequeo) = New HashSet(Of chequeo)
    Public Overridable Property nivel1 As nivel

End Class
