'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vehiculo
    Public Property id As Integer
    Public Property matricula As String
    Public Property color As String
    Public Property ano As Integer
    Public Property marca As String
    Public Property modelo As String
    Public Property chasis As String
    Public Property puertas As Integer
    Public Property activo As Boolean

    Public Overridable Property chequeos As ICollection(Of chequeo) = New HashSet(Of chequeo)
    Public Overridable Property permisoes As ICollection(Of permiso) = New HashSet(Of permiso)

End Class
